# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11server/auth.proto\x12\x08\x64istinct\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"?\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\".\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\x0b\x41uthService\x12\x38\n\x05Login\x12\x16.distinct.LoginRequest\x1a\x17.distinct.LoginResponse\x12\x38\n\x06Logout\x12\x17.distinct.LogoutRequest\x1a\x15.distinct.StatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=31
  _globals['_LOGINREQUEST']._serialized_end=81
  _globals['_LOGINRESPONSE']._serialized_start=83
  _globals['_LOGINRESPONSE']._serialized_end=146
  _globals['_LOGOUTREQUEST']._serialized_start=148
  _globals['_LOGOUTREQUEST']._serialized_end=178
  _globals['_STATUSREPLY']._serialized_start=180
  _globals['_STATUSREPLY']._serialized_end=226
  _globals['_AUTHSERVICE']._serialized_start=229
  _globals['_AUTHSERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
