# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server import auth_pb2 as server_dot_auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16server/inventory.proto\x12\x08\x64istinct\x1a\x11server/auth.proto\"D\n\x0bPostRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\x0b\n\x03qty\x18\x04 \x01(\x05\"6\n\nGetRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\"0\n\x04Item\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05stock\x18\x03 \x01(\x05\"M\n\x0bGetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.distinct.Item\x12\x0f\n\x07message\x18\x03 \x01(\t\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\".\n\tVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\x80\x01\n\rAppendRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x13\n\x0b\x63ommitIndex\x18\x05 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x06 \x03(\t\",\n\x0b\x41ppendReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32|\n\x10InventoryService\x12\x34\n\x04Post\x12\x15.distinct.PostRequest\x1a\x15.distinct.StatusReply\x12\x32\n\x03Get\x12\x14.distinct.GetRequest\x1a\x15.distinct.GetResponse2\x89\x01\n\x0bRaftService\x12\x39\n\x0bRequestVote\x12\x15.distinct.VoteRequest\x1a\x13.distinct.VoteReply\x12?\n\rAppendEntries\x12\x17.distinct.AppendRequest\x1a\x15.distinct.AppendReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTREQUEST']._serialized_start=55
  _globals['_POSTREQUEST']._serialized_end=123
  _globals['_GETREQUEST']._serialized_start=125
  _globals['_GETREQUEST']._serialized_end=179
  _globals['_ITEM']._serialized_start=181
  _globals['_ITEM']._serialized_end=229
  _globals['_GETRESPONSE']._serialized_start=231
  _globals['_GETRESPONSE']._serialized_end=308
  _globals['_VOTEREQUEST']._serialized_start=310
  _globals['_VOTEREQUEST']._serialized_end=401
  _globals['_VOTEREPLY']._serialized_start=403
  _globals['_VOTEREPLY']._serialized_end=449
  _globals['_APPENDREQUEST']._serialized_start=452
  _globals['_APPENDREQUEST']._serialized_end=580
  _globals['_APPENDREPLY']._serialized_start=582
  _globals['_APPENDREPLY']._serialized_end=626
  _globals['_INVENTORYSERVICE']._serialized_start=628
  _globals['_INVENTORYSERVICE']._serialized_end=752
  _globals['_RAFTSERVICE']._serialized_start=755
  _globals['_RAFTSERVICE']._serialized_end=892
# @@protoc_insertion_point(module_scope)
