# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import auth_pb2 as auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x08\x64istinct\x1a\nauth.proto\"D\n\x0bPostRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\x0b\n\x03qty\x18\x04 \x01(\x05\"6\n\nGetRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\"0\n\x04Item\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05stock\x18\x03 \x01(\x05\"M\n\x0bGetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.distinct.Item\x12\x0f\n\x07message\x18\x03 \x01(\t2|\n\x10InventoryService\x12\x34\n\x04Post\x12\x15.distinct.PostRequest\x1a\x15.distinct.StatusReply\x12\x32\n\x03Get\x12\x14.distinct.GetRequest\x1a\x15.distinct.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTREQUEST']._serialized_start=41
  _globals['_POSTREQUEST']._serialized_end=109
  _globals['_GETREQUEST']._serialized_start=111
  _globals['_GETREQUEST']._serialized_end=165
  _globals['_ITEM']._serialized_start=167
  _globals['_ITEM']._serialized_end=215
  _globals['_GETRESPONSE']._serialized_start=217
  _globals['_GETRESPONSE']._serialized_end=294
  _globals['_INVENTORYSERVICE']._serialized_start=296
  _globals['_INVENTORYSERVICE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
